services:
  drs-llm-environment:
    build:
      context: ..
      dockerfile: docker/Dockerfile.drs-llm-environment
      args:
        UID: ${UID}
        GID: ${GID}
        USERNAME: app
    image: drs-llm-environment:latest
    working_dir: /workspace
    environment:
      - HOME=/workspace
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ../:/workspace
      - ../../perf-pilot/LLMs:/LLMs:ro
    # ports:
    #   - "8080:8080"
    runtime: nvidia
    network_mode: host
    command: ["./docker/run_with_logs.sh"]
